### ISSUE TITLE
Crashes with ArgumentOutOfRangeException on some diffs

### ISSUE THREAD

**Issue by lassevk** [lassevk/DiffLib#9]
Seems that if the longest match is at the end of a collection, sometimes it tries to read past the end of the first/original collection.

**Comment by drewnoakes** [comment]
Is this issue fixed and available in a released NuGet package?

I need a diff utility and am evaluating this lib and also https://github.com/mmanela/diffplex.

**Comment by lassevk** [comment]
Yes, this is part of 2016.4.21.1027 of DiffLib available on Nuget.

**Comment by lassevk** [comment]
This was fixed in 2016.4.21.1027.
